### ISSUE TITLE
Make help command an embed

### ISSUE THREAD

**Issue by s-hfarooq** [s-hfarooq/QueenMoonBot#31]
Make the help command look better by making it an embed

**Comment by timot3** [comment]
Just migrate the bot to python at this point smh

**Comment by s-hfarooq** [comment]
q ww

**Comment by timot3** [comment]
![image](https://user-images.githubusercontent.com/48812670/83212204-0522fa00-a12d-11ea-91e8-455ce0131afd.png) 15 May 2020, that's when

**Comment by s-hfarooq** [comment]
Fixed in latest merge
